# Introduction of Auto-EDA tools

1. ðŸ“Š Dataprep ðŸ“š
2. ðŸ“Š AutoViz ðŸ“š
3. ðŸ“Š SweetViz ðŸ“š
4. ðŸ“Š D-Tale ðŸ“š


#### datasets:
* Titanic passengers


Based on https://www.kaggle.com/code/andreshg/automatic-eda-libraries-comparisson

In this notebook we are going to compare the top Auto EDA libraries that really facilite the dataset analysis and visualziation!

The main idea is that you can compare time to plot and results of each AutoEda library so you can select the best for your work.

In [1]:
!pip install pandas setuptools

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (1.5.3)
Requirement already satisfied: setuptools in c:\programdata\anaconda3\lib\site-packages (68.0.0)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2022.7)
Requirement already satisfied: numpy>=1.21.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [2]:
!pip install numpy==1.24.4

Defaulting to user installation because normal site-packages is not writeable
Collecting numpy==1.24.4
  Obtaining dependency information for numpy==1.24.4 from https://files.pythonhosted.org/packages/d8/ec/ebef2f7d7c28503f958f0f8b992e7ce606fb74f9e891199329d5f5f87404/numpy-1.24.4-cp311-cp311-win_amd64.whl.metadata
  Downloading numpy-1.24.4-cp311-cp311-win_amd64.whl.metadata (5.6 kB)
Downloading numpy-1.24.4-cp311-cp311-win_amd64.whl (14.8 MB)
   ---------------------------------------- 0.0/14.8 MB ? eta -:--:--
    --------------------------------------- 0.4/14.8 MB 11.6 MB/s eta 0:00:02
   -- ------------------------------------- 0.8/14.8 MB 10.6 MB/s eta 0:00:02
   ---- ----------------------------------- 1.5/14.8 MB 12.0 MB/s eta 0:00:02
   ------ --------------------------------- 2.5/14.8 MB 14.7 MB/s eta 0:00:01
   ---------- ----------------------------- 3.9/14.8 MB 17.6 MB/s eta 0:00:01
   -------------- ------------------------- 5.3/14.8 MB 20.1 MB/s eta 0:00:01
   ------------------ --------------------- 6.8/14.8 MB 21.9 MB/s eta 0:00:01
   ---------------------- ----------------- 8.3/14.8 MB 23.2 MB/s eta 0:00:01
   -------------------------- ------------- 9.8/14.8 MB 24.2 MB/s eta 0:00:01
   ------------------------------ --------- 11.3/14.8 MB 29.7 MB/s eta 0:00:01
   --------------------------------- ------ 12.4/14.8 MB 29.7 MB/s eta 0:00:01
   ----------------------------------- ---- 13.2/14.8 MB 28.4 MB/s eta 0:00:01
   ------------------------------------- -- 13.8/14.8 MB 29.8 MB/s eta 0:00:01
   ------------------------------------- -- 13.9/14.8 MB 26.2 MB/s eta 0:00:01
   ------------------------------------- -- 14.0/14.8 MB 22.6 MB/s eta 0:00:01
   -------------------------------------- - 14.1/14.8 MB 19.9 MB/s eta 0:00:01
   -------------------------------------- - 14.2/14.8 MB 19.3 MB/s eta 0:00:01
   ---------------------------------------  14.6/14.8 MB 17.2 MB/s eta 0:00:01
   ---------------------------------------  14.8/14.8 MB 17.2 MB/s eta 0:00:01
   ---------------------------------------  14.8/14.8 MB 17.2 MB/s eta 0:00:01
   ---------------------------------------- 14.8/14.8 MB 14.5 MB/s eta 0:00:00
Installing collected packages: numpy
Successfully installed numpy-1.24.4

  WARNING: The script f2py.exe is installed in 'C:\Users\sharafi\AppData\Roaming\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
tables 3.8.0 requires blosc2~=2.0.0, which is not installed.
tables 3.8.0 requires cython>=0.29.21, which is not installed.
transformers 2.1.1 requires sentencepiece, which is not installed.

In [10]:
import datetime as dt
import pandas as pd
import numpy as np
import os
import setuptools

#### Preparing the DataFrame

In [11]:
import os
# documentation: https://docs.python.org/3/library/os.html

# Set target directory path to SESSION 1 folder
new_path = r"C:\Users\sharafi\Dropbox\ML course\Data Analytics Course\Data Science Course WS2025"  # use raw string or double backslashes on Windows

# Change the current working directory
os.chdir(new_path)

# Optional: Verify current working directory
print("Current working directory:", os.getcwd())

Current working directory: C:\Users\sharafi\Dropbox\ML course\Data Analytics Course\Data Science Course WS2025

In [12]:
df = pd.concat([
        pd.read_csv('Input/Titanic/test.csv'),
        pd.read_csv('Input/Titanic/train.csv')
    ], axis=0)\
    .drop('Survived', axis=1)\
    .merge(
        pd.read_csv('Input/Titanic/gender_submission.csv'),
        on='PassengerId'
    )

df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,0
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,1
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,0
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,0
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,1

In [16]:
import re
df['Title']=df.Name.apply(lambda x: re.findall(', \w+.',x)[0][1:])

<a id='2'></a>
# <p style="background-color:skyblue; font-family:newtimeroman; font-size:150%; text-align:center">2. ðŸ“Š AutoViz ðŸ“š</p>

AutoViz stands out of the crowd of freeware Pythonic Rapid EDA Automation tools, doing things in a very fast way, the way better than its close freeware rivals like SweetViz or Pandas Profiling

In [17]:
!pip install autoviz

Defaulting to user installation because normal site-packages is not writeable
Collecting autoviz
  Obtaining dependency information for autoviz from https://files.pythonhosted.org/packages/51/92/eea3f91d7c5788a37eb739399cf99c3b2d3b6c1f25c1b9e51a2e85f2a00a/autoviz-0.1.905-py3-none-any.whl.metadata
  Using cached autoviz-0.1.905-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: xlrd in c:\users\sharafi\appdata\roaming\python\python311\site-packages (from autoviz) (2.0.2)
Collecting wordcloud (from autoviz)
  Obtaining dependency information for wordcloud from https://files.pythonhosted.org/packages/00/09/abb305dce85911b8fba382926cfc57f2f257729e25937fdcc63f3a1a67f9/wordcloud-1.9.4-cp311-cp311-win_amd64.whl.metadata
  Using cached wordcloud-1.9.4-cp311-cp311-win_amd64.whl.metadata (3.5 kB)
Collecting emoji (from autoviz)
  Obtaining dependency information for emoji from https://files.pythonhosted.org/packages/91/db/a0335710caaa6d0aebdaa65ad4df789c15d89b7babd9a30277838a7d9aac/emoji-2.14.1-py3-none-any.whl.metadata
  Using cached emoji-2.14.1-py3-none-any.whl.metadata (5.7 kB)
Collecting pyamg (from autoviz)
  Obtaining dependency information for pyamg from https://files.pythonhosted.org/packages/e5/7f/3e724b274f4dce9934f05f5df76ef17b4312dbffda11cb24b37ba47ada39/pyamg-5.3.0-cp311-cp311-win_amd64.whl.metadata
  Using cached pyamg-5.3.0-cp311-cp311-win_amd64.whl.metadata (8.3 kB)
Requirement already satisfied: scikit-learn in c:\programdata\anaconda3\lib\site-packages (from autoviz) (1.3.0)
Requirement already satisfied: statsmodels in c:\programdata\anaconda3\lib\site-packages (from autoviz) (0.14.0)
Requirement already satisfied: nltk in c:\programdata\anaconda3\lib\site-packages (from autoviz) (3.8.1)
Collecting textblob (from autoviz)
  Obtaining dependency information for textblob from https://files.pythonhosted.org/packages/1e/d6/40aa5aead775582ea0cf35870e5a3f16fab4b967f1ad2debe675f673f923/textblob-0.19.0-py3-none-any.whl.metadata
  Using cached textblob-0.19.0-py3-none-any.whl.metadata (4.4 kB)
Collecting xgboost<1.7,>=0.82 (from autoviz)
  Obtaining dependency information for xgboost<1.7,>=0.82 from https://files.pythonhosted.org/packages/24/14/d9ecb9fa86727f51bfb35f1c2b0428ebc6cd5ffde24c5e2dc583d3575a6f/xgboost-1.6.2-py3-none-win_amd64.whl.metadata
  Using cached xgboost-1.6.2-py3-none-win_amd64.whl.metadata (1.8 kB)
Requirement already satisfied: fsspec>=0.8.3 in c:\programdata\anaconda3\lib\site-packages (from autoviz) (2023.3.0)
Requirement already satisfied: typing-extensions>=4.1.1 in c:\programdata\anaconda3\lib\site-packages (from autoviz) (4.7.1)
Collecting pandas-dq>=1.29 (from autoviz)
  Obtaining dependency information for pandas-dq>=1.29 from https://files.pythonhosted.org/packages/ec/96/862c60b96e2abf218eec55d3b1e409b133de83f7a4f49c047aea9eeea927/pandas_dq-1.29-py3-none-any.whl.metadata
  Using cached pandas_dq-1.29-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.24.0 in c:\users\sharafi\appdata\roaming\python\python311\site-packages (from autoviz) (2.3.2)
Collecting hvplot>=0.9.2 (from autoviz)
  Obtaining dependency information for hvplot>=0.9.2 from https://files.pythonhosted.org/packages/06/51/b8cd6be4a303e6b88ca4b56feecf523f2a2e286ebd7cb56f0dbe986917f7/hvplot-0.12.0-py3-none-any.whl.metadata
  Using cached hvplot-0.12.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: holoviews>=1.16.0 in c:\programdata\anaconda3\lib\site-packages (from autoviz) (1.17.0)
Collecting panel>=1.4.0 (from autoviz)
  Obtaining dependency information for panel>=1.4.0 from https://files.pythonhosted.org/packages/f0/12/2d9700ddd550962e099d15ad94e6f7249bdf4402445b0004bcea49a00474/panel-1.7.5-py3-none-any.whl.metadata
  Using cached panel-1.7.5-py3-none-any.whl.metadata (15 kB)
Collecting pandas>=2.0 (from autoviz)
  Obtaining dependency information for pandas>=2.0 from https://files.pythonhosted.org/packages/a7/e7/ae86261695b6c8a36d6a4c8d5f9b9ede8248510d689a2f379a18354b37d7/pandas-2.3.2-cp311-cp311-win_amd64.whl.metadata
  Using cached pandas-2.3.2-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting matplotlib>3.7.4 (from autoviz)
  Obtaining dependency information for matplotlib>3.7.4 from https://files.pythonhosted.org/packages/b7/81/3200b792a5e8b354f31f4101ad7834743ad07b6d620259f2059317b25e4d/matplotlib-3.10.5-cp311-cp311-win_amd64.whl.metadata
  Using cached matplotlib-3.10.5-cp311-cp311-win_amd64.whl.metadata (11 kB)
Collecting seaborn>0.12.2 (from autoviz)
  Obtaining dependency information for seaborn>0.12.2 from https://files.pythonhosted.org/packages/83/11/00d3c3dfc25ad54e731d91449895a79e4bf2384dc3ac01809010ba88f6d5/seaborn-0.13.2-py3-none-any.whl.metadata
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: param<3.0,>=1.12.0 in c:\users\sharafi\appdata\roaming\python\python311\site-packages (from holoviews>=1.16.0->autoviz) (2.2.1)
Requirement already satisfied: pyviz-comms>=0.7.4 in c:\programdata\anaconda3\lib\site-packages (from holoviews>=1.16.0->autoviz) (2.3.0)
Requirement already satisfied: colorcet in c:\programdata\anaconda3\lib\site-packages (from holoviews>=1.16.0->autoviz) (3.0.1)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from holoviews>=1.16.0->autoviz) (23.0)
Requirement already satisfied: bokeh>=3.1 in c:\programdata\anaconda3\lib\site-packages (from hvplot>=0.9.2->autoviz) (3.2.1)
Collecting holoviews>=1.16.0 (from autoviz)
  Obtaining dependency information for holoviews>=1.16.0 from https://files.pythonhosted.org/packages/30/75/d451b9a0ab3a9c0b2c7d1d3cf0bcf797ccac420f3479476f9867e1737d39/holoviews-1.21.0-py3-none-any.whl.metadata
  Using cached holoviews-1.21.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>3.7.4->autoviz) (1.0.5)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>3.7.4->autoviz) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>3.7.4->autoviz) (4.25.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>3.7.4->autoviz) (1.4.4)
Requirement already satisfied: pillow>=8 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>3.7.4->autoviz) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>3.7.4->autoviz) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>3.7.4->autoviz) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=2.0->autoviz) (2022.7)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sharafi\appdata\roaming\python\python311\site-packages (from pandas>=2.0->autoviz) (2025.2)
Requirement already satisfied: bleach in c:\programdata\anaconda3\lib\site-packages (from panel>=1.4.0->autoviz) (4.1.0)
Collecting bokeh>=3.1 (from hvplot>=0.9.2->autoviz)
  Obtaining dependency information for bokeh>=3.1 from https://files.pythonhosted.org/packages/91/48/08b2382e739236aa3360b7976360ba3e0c043b6234e25951c18c1eb6fa06/bokeh-3.7.3-py3-none-any.whl.metadata
  Using cached bokeh-3.7.3-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: linkify-it-py in c:\programdata\anaconda3\lib\site-packages (from panel>=1.4.0->autoviz) (2.0.0)
Requirement already satisfied: markdown in c:\programdata\anaconda3\lib\site-packages (from panel>=1.4.0->autoviz) (3.4.1)
Requirement already satisfied: markdown-it-py in c:\programdata\anaconda3\lib\site-packages (from panel>=1.4.0->autoviz) (2.2.0)
Requirement already satisfied: mdit-py-plugins in c:\programdata\anaconda3\lib\site-packages (from panel>=1.4.0->autoviz) (0.3.0)
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (from panel>=1.4.0->autoviz) (2.31.0)
Requirement already satisfied: tqdm in c:\programdata\anaconda3\lib\site-packages (from panel>=1.4.0->autoviz) (4.65.0)
Requirement already satisfied: scipy>=1.5.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn->autoviz) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn->autoviz) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn->autoviz) (2.2.0)
Requirement already satisfied: click in c:\programdata\anaconda3\lib\site-packages (from nltk->autoviz) (8.0.4)
Requirement already satisfied: regex>=2021.8.3 in c:\programdata\anaconda3\lib\site-packages (from nltk->autoviz) (2022.7.9)
Collecting scipy>=1.5.0 (from scikit-learn->autoviz)
  Obtaining dependency information for scipy>=1.5.0 from https://files.pythonhosted.org/packages/c4/94/994369978509f227cba7dfb9e623254d0d5559506fe994aef4bea3ed469c/scipy-1.16.1-cp311-cp311-win_amd64.whl.metadata
  Using cached scipy-1.16.1-cp311-cp311-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: patsy>=0.5.2 in c:\programdata\anaconda3\lib\site-packages (from statsmodels->autoviz) (0.5.3)
Collecting nltk (from autoviz)
  Obtaining dependency information for nltk from https://files.pythonhosted.org/packages/4d/66/7d9e26593edda06e8cb531874633f7c2372279c3b0f46235539fe546df8b/nltk-3.9.1-py3-none-any.whl.metadata
  Using cached nltk-3.9.1-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: Jinja2>=2.9 in c:\programdata\anaconda3\lib\site-packages (from bokeh>=3.1->hvplot>=0.9.2->autoviz) (3.1.2)
Collecting contourpy>=1.0.1 (from matplotlib>3.7.4->autoviz)
  Obtaining dependency information for contourpy>=1.0.1 from https://files.pythonhosted.org/packages/98/4b/9bd370b004b5c9d8045c6c33cf65bae018b27aca550a3f657cdc99acdbd8/contourpy-1.3.3-cp311-cp311-win_amd64.whl.metadata
  Using cached contourpy-1.3.3-cp311-cp311-win_amd64.whl.metadata (5.5 kB)
Collecting narwhals>=1.13 (from bokeh>=3.1->hvplot>=0.9.2->autoviz)
  Obtaining dependency information for narwhals>=1.13 from https://files.pythonhosted.org/packages/dd/54/1ecca75e51d7da8ca53d1ffa8636ef9077a6eaa31f43ade71360b3e6449a/narwhals-2.2.0-py3-none-any.whl.metadata
  Using cached narwhals-2.2.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: PyYAML>=3.10 in c:\programdata\anaconda3\lib\site-packages (from bokeh>=3.1->hvplot>=0.9.2->autoviz) (6.0)
Requirement already satisfied: tornado>=6.2 in c:\programdata\anaconda3\lib\site-packages (from bokeh>=3.1->hvplot>=0.9.2->autoviz) (6.3.2)
Requirement already satisfied: xyzservices>=2021.09.1 in c:\programdata\anaconda3\lib\site-packages (from bokeh>=3.1->hvplot>=0.9.2->autoviz) (2022.9.0)
Requirement already satisfied: pyct>=0.4.4 in c:\programdata\anaconda3\lib\site-packages (from colorcet->holoviews>=1.16.0->autoviz) (0.5.0)
Requirement already satisfied: six in c:\programdata\anaconda3\lib\site-packages (from patsy>=0.5.2->statsmodels->autoviz) (1.16.0)
Requirement already satisfied: webencodings in c:\programdata\anaconda3\lib\site-packages (from bleach->panel>=1.4.0->autoviz) (0.5.1)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from click->nltk->autoviz) (0.4.6)
Requirement already satisfied: uc-micro-py in c:\programdata\anaconda3\lib\site-packages (from linkify-it-py->panel>=1.4.0->autoviz) (1.0.1)
Requirement already satisfied: mdurl~=0.1 in c:\programdata\anaconda3\lib\site-packages (from markdown-it-py->panel>=1.4.0->autoviz) (0.1.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests->panel>=1.4.0->autoviz) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests->panel>=1.4.0->autoviz) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests->panel>=1.4.0->autoviz) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sharafi\appdata\roaming\python\python311\site-packages (from requests->panel>=1.4.0->autoviz) (2025.7.14)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\sharafi\appdata\roaming\python\python311\site-packages (from Jinja2>=2.9->bokeh>=3.1->hvplot>=0.9.2->autoviz) (2.1.3)
Using cached autoviz-0.1.905-py3-none-any.whl (67 kB)
Using cached hvplot-0.12.0-py3-none-any.whl (175 kB)
Using cached holoviews-1.21.0-py3-none-any.whl (5.9 MB)
Using cached matplotlib-3.10.5-cp311-cp311-win_amd64.whl (8.1 MB)
Using cached pandas-2.3.2-cp311-cp311-win_amd64.whl (11.3 MB)
Using cached pandas_dq-1.29-py3-none-any.whl (29 kB)
Using cached panel-1.7.5-py3-none-any.whl (29.5 MB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached xgboost-1.6.2-py3-none-win_amd64.whl (125.4 MB)
Using cached emoji-2.14.1-py3-none-any.whl (590 kB)
Using cached pyamg-5.3.0-cp311-cp311-win_amd64.whl (1.7 MB)
Using cached textblob-0.19.0-py3-none-any.whl (624 kB)
Using cached nltk-3.9.1-py3-none-any.whl (1.5 MB)
Using cached wordcloud-1.9.4-cp311-cp311-win_amd64.whl (299 kB)
Using cached bokeh-3.7.3-py3-none-any.whl (7.0 MB)
Using cached contourpy-1.3.3-cp311-cp311-win_amd64.whl (225 kB)
Using cached scipy-1.16.1-cp311-cp311-win_amd64.whl (38.6 MB)
Using cached narwhals-2.2.0-py3-none-any.whl (401 kB)
Installing collected packages: scipy, narwhals, emoji, contourpy, xgboost, pyamg, pandas, nltk, matplotlib, wordcloud, textblob, seaborn, pandas-dq, bokeh, panel, holoviews, hvplot, autoviz
  Attempting uninstall: xgboost
    Found existing installation: xgboost 2.0.3
    Uninstalling xgboost-2.0.3:
      Successfully uninstalled xgboost-2.0.3
Successfully installed autoviz-0.1.905 bokeh-3.7.3 contourpy-1.3.3 emoji-2.14.1 holoviews-1.21.0 hvplot-0.12.0 matplotlib-3.10.5 narwhals-2.2.0 nltk-3.9.1 pandas-2.3.2 pandas-dq-1.29 panel-1.7.5 pyamg-5.3.0 scipy-1.16.1 seaborn-0.13.2 textblob-0.19.0 wordcloud-1.9.4 xgboost-1.6.2

  WARNING: The script nltk.exe is installed in 'C:\Users\sharafi\AppData\Roaming\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script wordcloud_cli.exe is installed in 'C:\Users\sharafi\AppData\Roaming\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script bokeh.exe is installed in 'C:\Users\sharafi\AppData\Roaming\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script panel.exe is installed in 'C:\Users\sharafi\AppData\Roaming\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script holoviews.exe is installed in 'C:\Users\sharafi\AppData\Roaming\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.

In [18]:
# Start of AutoViz process
start_time = dt.datetime.now()
print("Started at ", start_time)

Started at  2025-08-25 13:52:59.503845

In [19]:
!pip install jinja2==3.1.2
!pip install markupsafe==2.1.3

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: jinja2==3.1.2 in c:\programdata\anaconda3\lib\site-packages (3.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\sharafi\appdata\roaming\python\python311\site-packages (from jinja2==3.1.2) (2.1.3)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: markupsafe==2.1.3 in c:\users\sharafi\appdata\roaming\python\python311\site-packages (2.1.3)

In [21]:
import pandas as pd
print("Pandas version:", pd.__version__)
import jinja2
print("Jinja2 version:", jinja2.__version__)    
import autoviz
print("AutoViz version:", autoviz.__version__)

Pandas version: 1.5.3
Jinja2 version: 3.1.2

ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "c:\ProgramData\anaconda3\python.exe"
  * The NumPy version is: "1.24.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.

ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "c:\ProgramData\anaconda3\python.exe"
  * The NumPy version is: "1.24.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.

In [22]:
from autoviz.AutoViz_Class import AutoViz_Class

AV = AutoViz_Class()
dftc = AV.AutoViz(
    filename='',
    sep='' ,
    depVar='Survived',
    dfte=df,
    header=0,
    verbose=1,
    lowess=False,
    chart_format='png',
    max_rows_analyzed=300000,
    max_cols_analyzed=30
)

ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "c:\ProgramData\anaconda3\python.exe"
  * The NumPy version is: "1.24.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.

In [ ]:
print('AutoViz finished!!')
finish_time = dt.datetime.now()
print("Finished at ", finish_time)
elapsed = finish_time - start_time
print("Elapsed time: ", elapsed)

AutoViz finished!!
Finished at  2025-08-11 17:36:58.336362
Elapsed time:  0:00:19.589024

<a id='3'></a>
# <p style="background-color:skyblue; font-family:newtimeroman; font-size:150%; text-align:center">3. ðŸ“Š SweetViz ðŸ“š</p>

In [ ]:
pip install sweetviz

Requirement already satisfied: sweetviz in c:\users\baner\anaconda3\envs\global_use\lib\site-packages (2.1.4)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3 in c:\users\baner\anaconda3\envs\global_use\lib\site-packages (from sweetviz) (1.5.3)
Requirement already satisfied: numpy>=1.16.0 in c:\users\baner\anaconda3\envs\global_use\lib\site-packages (from sweetviz) (1.24.4)
Requirement already satisfied: matplotlib>=3.1.3 in c:\users\baner\anaconda3\envs\global_use\lib\site-packages (from sweetviz) (3.7.1)
Requirement already satisfied: tqdm>=4.43.0 in c:\users\baner\anaconda3\envs\global_use\lib\site-packages (from sweetviz) (4.67.1)
Requirement already satisfied: scipy>=1.3.2 in c:\users\baner\anaconda3\envs\global_use\lib\site-packages (from sweetviz) (1.15.3)
Requirement already satisfied: jinja2>=2.11.1 in c:\users\baner\anaconda3\envs\global_use\lib\site-packages (from sweetviz) (3.1.2)
Requirement already satisfied: importlib-resources>=1.2.0 in c:\users\baner\anaconda3\envs\global_use\lib\site-packages (from sweetviz) (6.5.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\baner\anaconda3\envs\global_use\lib\site-packages (from jinja2>=2.11.1->sweetviz) (2.1.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\baner\anaconda3\envs\global_use\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\baner\anaconda3\envs\global_use\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\baner\anaconda3\envs\global_use\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (4.59.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\baner\anaconda3\envs\global_use\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\baner\anaconda3\envs\global_use\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (25.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\baner\anaconda3\envs\global_use\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\baner\anaconda3\envs\global_use\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\baner\anaconda3\envs\global_use\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\baner\anaconda3\envs\global_use\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\baner\anaconda3\envs\global_use\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.1.3->sweetviz) (1.17.0)
Requirement already satisfied: colorama in c:\users\baner\appdata\roaming\python\python311\site-packages (from tqdm>=4.43.0->sweetviz) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~atplotlib (c:\Users\baner\anaconda3\envs\Global_use\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (c:\Users\baner\anaconda3\envs\Global_use\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (c:\Users\baner\anaconda3\envs\Global_use\Lib\site-packages)

In [ ]:
import sweetviz as sv

In [ ]:
# Start of Pandas Profiling process
start_time = dt.datetime.now()
print("Started at ", start_time)

Started at  2025-08-11 17:36:59.466663

In [ ]:
advert_report = sv.analyze(df)

                                             |          | [  0%]   00:00 -> (? left)

AttributeError: module 'numpy' has no attribute 'warnings'

In [ ]:
advert_report.show_html()

Report SWEETVIZ_REPORT.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [ ]:
advert_report = sv.compare(df[df['Survived']==0],df[df['Survived']==1])

                                             |          | [  0%]   00:00 -> (? left)

In [ ]:
advert_report.show_html()

Report SWEETVIZ_REPORT.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [ ]:
print('SweetViz finished!!')
finish_time = dt.datetime.now()
print("Finished at ", finish_time)
elapsed = finish_time - start_time
print("Elapsed time: ", elapsed)

SweetViz finished!!
Finished at  2025-08-05 21:50:51.181982
Elapsed time:  0:00:22.651298

In [ ]:
#!pip install lux-api

In [ ]:
import lux
import pandas as pd

In [ ]:
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived,Title
0,892,3,"Kelly, Mr. James",male,34.50,0,0,330911,7.8292,NaN,Q,0,Mr.
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00,1,0,363272,7.0000,NaN,S,1,Mrs.
2,894,2,"Myles, Mr. Thomas Francis",male,62.00,0,0,240276,9.6875,NaN,Q,0,Mr.
3,895,3,"Wirz, Mr. Albert",male,27.00,0,0,315154,8.6625,NaN,S,0,Mr.
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00,1,1,3101298,12.2875,NaN,S,1,Mrs.
5,897,3,"Svensson, Mr. Johan Cervin",male,14.00,0,0,7538,9.2250,NaN,S,0,Mr.
6,898,3,"Connolly, Miss. Kate",female,30.00,0,0,330972,7.6292,NaN,Q,1,Miss.
7,899,2,"Caldwell, Mr. Albert Francis",male,26.00,1,1,248738,29.0000,NaN,S,0,Mr.
8,900,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.00,0,0,2657,7.2292,NaN,C,1,Mrs.
9,901,3,"Davies, Mr. John Samuel",male,21.00,2,0,A/4 48871,24.1500,NaN,S,0,Mr.
10,902,3,"Ilieff, Mr. Ylio",male,NaN,0,0,349220,7.8958,NaN,S,0,Mr.
11,903,1,"Jones, Mr. Charles Cresson",male,46.00,0,0,694,26.0000,NaN,S,0,Mr.
12,904,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23.00,1,0,21228,82.2667,B45,S,1,Mrs.
13,905,2,"Howard, Mr. Benjamin",male,63.00,1,0,24065,26.0000,NaN,S,0,Mr.
14,906,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance Toogood)",female,47.00,1,0,W.E.P. 5734,61.1750,E31,S,1,Mrs.
15,907,2,"del Carlo, Mrs. Sebastiano (Argenia Genovesi)",female,24.00,1,0,SC/PARIS 2167,27.7208,NaN,C,1,Mrs.
16,908,2,"Keane, Mr. Daniel",male,35.00,0,0,233734,12.3500,NaN,Q,0,Mr.
17,909,3,"Assaf, Mr. Gerios",male,21.00,0,0,2692,7.2250,NaN,C,0,Mr.
18,910,3,"Ilmakangas, Miss. Ida Livija",female,27.00,1,0,STON/O2. 3101270,7.9250,NaN,S,1,Miss.
19,911,3,"Assaf Khalil, Mrs. Mariana (Miriam"")""",female,45.00,0,0,2696,7.2250,NaN,C,1,Mrs.
20,912,1,"Rothschild, Mr. Martin",male,55.00,1,0,PC 17603,59.4000,NaN,C,0,Mr.
21,913,3,"Olsen, Master. Artur Karl",male,9.00,0,1,C 17368,3.1708,NaN,S,0,Master.
22,914,1,"Flegenheim, Mrs. Alfred (Antoinette)",female,NaN,0,0,PC 17598,31.6833,NaN,S,1,Mrs.
23,915,1,"Williams, Mr. Richard Norris II",male,21.00,0,1,PC 17597,61.3792,NaN,C,0,Mr.
24,916,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,48.00,1,3,PC 17608,262.3750,B57 B59 B63 B66,C,1,Mrs.
25,917,3,"Robins, Mr. Alexander A",male,50.00,1,0,A/5. 3337,14.5000,NaN,S,0,Mr.
26,918,1,"Ostby, Miss. Helene Ragnhild",female,22.00,0,1,113509,61.9792,B36,C,1,Miss.
27,919,3,"Daher, Mr. Shedid",male,22.50,0,0,2698,7.2250,NaN,C,0,Mr.
28,920,1,"Brady, Mr. John Bertram",male,41.00,0,0,113054,30.5000,A21,S,0,Mr.
29,921,3,"Samaan, Mr. Elias",male,NaN,2,0,2662,21.6792,NaN,C,0,Mr.
30,922,2,"Louch, Mr. Charles Alexander",male,50.00,1,0,SC/AH 3085,26.0000,NaN,S,0,Mr.
31,923,2,"Jefferys, Mr. Clifford Thomas",male,24.00,2,0,C.A. 31029,31.5000,NaN,S,0,Mr.
32,924,3,"Dean, Mrs. Bertram (Eva Georgetta Light)",female,33.00,1,2,C.A. 2315,20.5750,NaN,S,1,Mrs.
33,925,3,"Johnston, Mrs. Andrew G (Elizabeth Lily"" Watson)""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,1,Mrs.
34,926,1,"Mock, Mr. Philipp Edmund",male,30.00,1,0,13236,57.7500,C78,C,0,Mr.
35,927,3,"Katavelas, Mr. Vassilios (Catavelas Vassilios"")""",male,18.50,0,0,2682,7.2292,NaN,C,0,Mr.
36,928,3,"Roth, Miss. Sarah A",female,NaN,0,0,342712,8.0500,NaN,S,1,Miss.
37,929,3,"Cacic, Miss. Manda",female,21.00,0,0,315087,8.6625,NaN,S,1,Miss.
38,930,3,"Sap, Mr. Julius",male,25.00,0,0,345768,9.5000,NaN,S,0,Mr.
39,931,3,"Hee, Mr. Ling",male,NaN,0,0,1601,56.4958,NaN,S,0,Mr.
40,932,3,"Karun, Mr. Franz",male,39.00,0,1,349256,13.4167,NaN,C,0,Mr.
41,933,1,"Franklin, Mr. Thomas Parham",male,NaN,0,0,113778,26.5500,D34,S,0,Mr.
42,934,3,"Goldsmith, Mr. Nathan",male,41.00,0,0,SOTON/O.Q. 3101263,7.8500,NaN,S,0,Mr.
43,935,2,"Corbett, Mrs. Walter H (Irene Colvin)",female,30.00,0,0,237249,13.0000,NaN,S,1,Mrs.
44,936,1,"Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons)",female,45.00,1,0,11753,52.5542,D19,S,1,Mrs.
45,937,3,"Peltomaki, Mr. Nikolai Johannes",male,25.00,0,0,STON/O 2. 3101291,7.9250,NaN,S,0,Mr.
46,938,1,"Chevre, Mr. Paul Romaine",male,45.00,0,0,PC 17594,29.7000,A9,C,0,Mr.
47,939,3,"Shaughnessy, Mr. Patrick",male,NaN,0,0,370374,7.7500,NaN,Q,0,Mr.
48,940,1,"Bucknell, Mrs. William Robert (Emma Eliza Ward)",female,60.00,0,0,11813,76.2917,D15,C,1,Mrs.
49,941,3,"Coutts, Mrs. William (Winnie Minnie"" Treanor)""",female,36.00,0,2,C.A. 37671,15.9000,NaN,S,1,Mrs.
50,942,1,"Smith, Mr. Lucien Philip",male,24.00,1,0,13695,60.0000,C31,S,0,Mr.
51,943,2,"Pulbaum, Mr. Franz",male,27.00,0,0,SC/PARIS 2168,15.0333,NaN,C,0,Mr.
52,944,2,"Hocking, Miss. Ellen Nellie""""",female,20.00,2,1,29105,23.0000,NaN,S,1,Miss.
53,945,1,"Fortune, Miss. Ethel Flora",female,28.00,3,2,19950,263.0000,C23 C25 C27,S,1,Miss.
54,946,2,"Mangiavacchi, Mr. Serafino Emilio",male,NaN,0,0,SC/A.3 2861,15.5792,NaN,C,0,Mr.
55,947,3,"Rice, Master. Albert",male,10.00,4,1,382652,29.1250,NaN,Q,0,Master.
56,948,3,"Cor, Mr. Bartol",male,35.00,0,0,349230,7.8958,NaN,S,0,Mr.
57,949,3,"Abelseth, Mr. Olaus Jorgensen",male,25.00,0,0,348122,7.6500,F G63,S,0,Mr.
58,950,3,"Davison, Mr. Thomas Henry",male,NaN,1,0,386525,16.1000,NaN,S,0,Mr.
59,951,1,"Chaudanson, Miss. Victorine",female,36.00,0,0,PC 17608,262.3750,B61,C,1,Miss.
60,952,3,"Dika, Mr. Mirko",male,17.00,0,0,349232,7.8958,NaN,S,0,Mr.
61,953,2,"McCrae, Mr. Arthur Gordon",male,32.00,0,0,237216,13.5000,NaN,S,0,Mr.
62,954,3,"Bjorklund, Mr. Ernst Herbert",male,18.00,0,0,347090,7.7500,NaN,S,0,Mr.
63,955,3,"Bradley, Miss. Bridget Delia",female,22.00,0,0,334914,7.7250,NaN,Q,1,Miss.
64,956,1,"Ryerson, Master. John Borie",male,13.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C,0,Master.
65,957,2,"Corey, Mrs. Percy C (Mary Phyllis Elizabeth Miller)",female,NaN,0,0,F.C.C. 13534,21.0000,NaN,S,1,Mrs.
66,958,3,"Burns, Miss. Mary Delia",female,18.00,0,0,330963,7.8792,NaN,Q,1,Miss.
67,959,1,"Moore, Mr. Clarence Bloomfield",male,47.00,0,0,113796,42.4000,NaN,S,0,Mr.
68,960,1,"Tucker, Mr. Gilbert Milligan Jr",male,31.00,0,0,2543,28.5375,C53,C,0,Mr.
69,961,1,"Fortune, Mrs. Mark (Mary McDougald)",female,60.00,1,4,19950,263.0000,C23 C25 C27,S,1,Mrs.
70,962,3,"Mulvihill, Miss. Bertha E",female,24.00,0,0,382653,7.7500,NaN,Q,1,Miss.
71,963,3,"Minkoff, Mr. Lazar",male,21.00,0,0,349211,7.8958,NaN,S,0,Mr.
72,964,3,"Nieminen, Miss. Manta Josefina",female,29.00,0,0,3101297,7.9250,NaN,S,1,Miss.
73,965,1,"Ovies y Rodriguez, Mr. Servando",male,28.50,0,0,PC 17562,27.7208,D43,C,0,Mr.
74,966,1,"Geiger, Miss. Amalie",female,35.00,0,0,113503,211.5000,C130,C,1,Miss.
75,967,1,"Keeping, Mr. Edwin",male,32.50,0,0,113503,211.5000,C132,C,0,Mr.
76,968,3,"Miles, Mr. Frank",male,NaN,0,0,359306,8.0500,NaN,S,0,Mr.
77,969,1,"Cornell, Mrs. Robert Clifford (Malvina Helen Lamson)",female,55.00,2,0,11770,25.7000,C101,S,1,Mrs.
78,970,2,"Aldworth, Mr. Charles Augustus",male,30.00,0,0,248744,13.0000,NaN,S,0,Mr.
79,971,3,"Doyle, Miss. Elizabeth",female,24.00,0,0,368702,7.7500,NaN,Q,1,Miss.
80,972,3,"Boulos, Master. Akar",male,6.00,1,1,2678,15.2458,NaN,C,0,Master.
81,973,1,"Straus, Mr. Isidor",male,67.00,1,0,PC 17483,221.7792,C55 C57,S,0,Mr.
82,974,1,"Case, Mr. Howard Brown",male,49.00,0,0,19924,26.0000,NaN,S,0,Mr.
83,975,3,"Demetri, Mr. Marinko",male,NaN,0,0,349238,7.8958,NaN,S,0,Mr.
84,976,2,"Lamb, Mr. John Joseph",male,NaN,0,0,240261,10.7083,NaN,Q,0,Mr.
85,977,3,"Khalil, Mr. Betros",male,NaN,1,0,2660,14.4542,NaN,C,0,Mr.
86,978,3,"Barry, Miss. Julia",female,27.00,0,0,330844,7.8792,NaN,Q,1,Miss.
87,979,3,"Badman, Miss. Emily Louisa",female,18.00,0,0,A/4 31416,8.0500,NaN,S,1,Miss.
88,980,3,"O'Donoghue, Ms. Bridget",female,NaN,0,0,364856,7.7500,NaN,Q,1,Ms.
89,981,2,"Wells, Master. Ralph Lester",male,2.00,1,1,29103,23.0000,NaN,S,0,Master.
90,982,3,"Dyker, Mrs. Adolf Fredrik (Anna Elisabeth Judith Andersson)",female,22.00,1,0,347072,13.9000,NaN,S,1,Mrs.
91,983,3,"Pedersen, Mr. Olaf",male,NaN,0,0,345498,7.7750,NaN,S,0,Mr.
92,984,1,"Davidson, Mrs. Thornton (Orian Hays)",female,27.00,1,2,F.C. 12750,52.0000,B71,S,1,Mrs.
93,985,3,"Guest, Mr. Robert",male,NaN,0,0,376563,8.0500,NaN,S,0,Mr.
94,986,1,"Birnbaum, Mr. Jakob",male,25.00,0,0,13905,26.0000,NaN,C,0,Mr.
95,987,3,"Tenglin, Mr. Gunnar Isidor",male,25.00,0,0,350033,7.7958,NaN,S,0,Mr.
96,988,1,"Cavendish, Mrs. Tyrell William (Julia Florence Siegel)",female,76.00,1,0,19877,78.8500,C46,S,1,Mrs.
97,989,3,"Makinen, Mr. Kalle Edvard",male,29.00,0,0,STON/O 2. 3101268,7.9250,NaN,S,0,Mr.
98,990,3,"Braf, Miss. Elin Ester Maria",female,20.00,0,0,347471,7.8542,NaN,S,1,Miss.
99,991,3,"Nancarrow, Mr. William Henry",male,33.00,0,0,A./5. 3338,8.0500,NaN,S,0,Mr.
100,992,1,"Stengel, Mrs. Charles Emil Henry (Annie May Morris)",female,43.00,1,0,11778,55.4417,C116,C,1,Mrs.
101,993,2,"Weisz, Mr. Leopold",male,27.00,1,0,228414,26.0000,NaN,S,0,Mr.
102,994,3,"Foley, Mr. William",male,NaN,0,0,365235,7.7500,NaN,Q,0,Mr.
103,995,3,"Johansson Palmquist, Mr. Oskar Leander",male,26.00,0,0,347070,7.7750,NaN,S,0,Mr.
104,996,3,"Thomas, Mrs. Alexander (Thamine Thelma"")""",female,16.00,1,1,2625,8.5167,NaN,C,1,Mrs.
105,997,3,"Holthen, Mr. Johan Martin",male,28.00,0,0,C 4001,22.5250,NaN,S,0,Mr.
106,998,3,"Buckley, Mr. Daniel",male,21.00,0,0,330920,7.8208,NaN,Q,0,Mr.
107,999,3,"Ryan, Mr. Edward",male,NaN,0,0,383162,7.7500,NaN,Q,0,Mr.
108,1000,3,"Willer, Mr. Aaron (Abi Weller"")""",male,NaN,0,0,3410,8.7125,NaN,S,0,Mr.
109,1001,2,"Swane, Mr. George",male,18.50,0,0,248734,13.0000,F,S,0,Mr.
110,1002,2,"Stanton, Mr. Samuel Ward",male,41.00,0,0,237734,15.0458,NaN,C,0,Mr.
111,1003,3,"Shine, Miss. Ellen Natalia",female,NaN,0,0,330968,7.7792,NaN,Q,1,Miss.
112,1004,1,"Evans, Miss. Edith Corse",female,36.00,0,0,PC 17531,31.6792,A29,C,1,Miss.
113,1005,3,"Buckley, Miss. Katherine",female,18.50,0,0,329944,7.2833,NaN,Q,1,Miss.
114,1006,1,"Straus, Mrs. Isidor (Rosalie Ida Blun)",female,63.00,1,0,PC 17483,221.7792,C55 C57,S,1,Mrs.
115,1007,3,"Chronopoulos, Mr. Demetrios",male,18.00,1,0,2680,14.4542,NaN,C,0,Mr.
116,1008,3,"Thomas, Mr. John",male,NaN,0,0,2681,6.4375,NaN,C,0,Mr.
117,1009,3,"Sandstrom, Miss. Beatrice Irene",female,1.00,1,1,PP 9549,16.7000,G6,S,1,Miss.
118,1010,1,"Beattie, Mr. Thomson",male,36.00,0,0,13050,75.2417,C6,C,0,Mr.
119,1011,2,"Chapman, Mrs. John Henry (Sara Elizabeth Lawry)",female,29.00,1,0,SC/AH 29037,26.0000,NaN,S,1,Mrs.
120,1012,2,"Watt, Miss. Bertha J",female,12.00,0,0,C.A. 33595,15.7500,NaN,S,1,Miss.
121,1013,3,"Kiernan, Mr. John",male,NaN,1,0,367227,7.7500,NaN,Q,0,Mr.
122,1014,1,"Schabert, Mrs. Paul (Emma Mock)",female,35.00,1,0,13236,57.7500,C28,C,1,Mrs.
123,1015,3,"Carver, Mr. Alfred John",male,28.00,0,0,392095,7.2500,NaN,S,0,Mr.
124,1016,3,"Kennedy, Mr. John",male,NaN,0,0,368783,7.7500,NaN,Q,0,Mr.
125,1017,3,"Cribb, Miss. Laura Alice",female,17.00,0,1,371362,16.1000,NaN,S,1,Miss.
126,1018,3,"Brobeck, Mr. Karl Rudolf",male,22.00,0,0,350045,7.7958,NaN,S,0,Mr.
127,1019,3,"McCoy, Miss. Alicia",female,NaN,2,0,367226,23.2500,NaN,Q,1,Miss.
128,1020,2,"Bowenur, Mr. Solomon",male,42.00,0,0,211535,13.0000,NaN,S,0,Mr.
129,1021,3,"Petersen, Mr. Marius",male,24.00,0,0,342441,8.0500,NaN,S,0,Mr.
130,1022,3,"Spinner, Mr. Henry John",male,32.00,0,0,STON/OQ. 369943,8.0500,NaN,S,0,Mr.
131,1023,1,"Gracie, Col. Archibald IV",male,53.00,0,0,113780,28.5000,C51,C,0,Col.
132,1024,3,"Lefebre, Mrs. Frank (Frances)",female,NaN,0,4,4133,25.4667,NaN,S,1,Mrs.
133,1025,3,"Thomas, Mr. Charles P",male,NaN,1,0,2621,6.4375,NaN,C,0,Mr.
134,1026,3,"Dintcheff, Mr. Valtcho",male,43.00,0,0,349226,7.8958,NaN,S,0,Mr.
135,1027,3,"Carlsson, Mr. Carl Robert",male,24.00,0,0,350409,7.8542,NaN,S,0,Mr.
136,1028,3,"Zakarian, Mr. Mapriededer",male,26.50,0,0,2656,7.2250,NaN,C,0,Mr.
137,1029,2,"Schmidt, Mr. August",male,26.00,0,0,248659,13.0000,NaN,S,0,Mr.
138,1030,3,"Drapkin, Miss. Jennie",female,23.00,0,0,SOTON/OQ 392083,8.0500,NaN,S,1,Miss.
139,1031,3,"Goodwin, Mr. Charles Frederick",male,40.00,1,6,CA 2144,46.9000,NaN,S,0,Mr.
140,1032,3,"Goodwin, Miss. Jessie Allis",female,10.00,5,2,CA 2144,46.9000,NaN,S,1,Miss.
141,1033,1,"Daniels, Miss. Sarah",female,33.00,0,0,113781,151.5500,NaN,S,1,Miss.
142,1034,1,"Ryerson, Mr. Arthur Larned",male,61.00,1,3,PC 17608,262.3750,B57 B59 B63 B66,C,0,Mr.
143,1035,2,"Beauchamp, Mr. Henry James",male,28.00,0,0,244358,26.0000,NaN,S,0,Mr.
144,1036,1,"Lindeberg-Lind, Mr. Erik Gustaf (Mr Edward Lingrey"")""",male,42.00,0,0,17475,26.5500,NaN,S,0,Mr.
145,1037,3,"Vander Planke, Mr. Julius",male,31.00,3,0,345763,18.0000,NaN,S,0,Mr.
146,1038,1,"Hilliard, Mr. Herbert Henry",male,NaN,0,0,17463,51.8625,E46,S,0,Mr.
147,1039,3,"Davies, Mr. Evan",male,22.00,0,0,SC/A4 23568,8.0500,NaN,S,0,Mr.
148,1040,1,"Crafton, Mr. John Bertram",male,NaN,0,0,113791,26.5500,NaN,S,0,Mr.
149,1041,2,"Lahtinen, Rev. William",male,30.00,1,1,250651,26.0000,NaN,S,0,Rev.
150,1042,1,"Earnshaw, Mrs. Boulton (Olive Potter)",female,23.00,0,1,11767,83.1583,C54,C,1,Mrs.
151,1043,3,"Matinoff, Mr. Nicola",male,NaN,0,0,349255,7.8958,NaN,C,0,Mr.
152,1044,3,"Storey, Mr. Thomas",male,60.50,0,0,3701,NaN,NaN,S,0,Mr.
153,1045,3,"Klasen, Mrs. (Hulda Kristina Eugenia Lofqvist)",female,36.00,0,2,350405,12.1833,NaN,S,1,Mrs.
154,1046,3,"Asplund, Master. Filip Oscar",male,13.00,4,2,347077,31.3875,NaN,S,0,Master.
155,1047,3,"Duquemin, Mr. Joseph",male,24.00,0,0,S.O./P.P. 752,7.5500,NaN,S,0,Mr.
156,1048,1,"Bird, Miss. Ellen",female,29.00,0,0,PC 17483,221.7792,C97,S,1,Miss.
157,1049,3,"Lundin, Miss. Olga Elida",female,23.00,0,0,347469,7.8542,NaN,S,1,Miss.
158,1050,1,"Borebank, Mr. John James",male,42.00,0,0,110489,26.5500,D22,S,0,Mr.
159,1051,3,"Peacock, Mrs. Benjamin (Edith Nile)",female,26.00,0,2,SOTON/O.Q. 3101315,13.7750,NaN,S,1,Mrs.
160,1052,3,"Smyth, Miss. Julia",female,NaN,0,0,335432,7.7333,NaN,Q,1,Miss.
161,1053,3,"Touma, Master. Georges Youssef",male,7.00,1,1,2650,15.2458,NaN,C,0,Master.
162,1054,2,"Wright, Miss. Marion",female,26.00,0,0,220844,13.5000,NaN,S,1,Miss.
163,1055,3,"Pearce, Mr. Ernest",male,NaN,0,0,343271,7.0000,NaN,S,0,Mr.
164,1056,2,"Peruschitz, Rev. Joseph Maria",male,41.00,0,0,237393,13.0000,NaN,S,0,Rev.
165,1057,3,"Kink-Heilmann, Mrs. Anton (Luise Heilmann)",female,26.00,1,1,315153,22.0250,NaN,S,1,Mrs.
166,1058,1,"Brandeis, Mr. Emil",male,48.00,0,0,PC 17591,50.4958,B10,C,0,Mr.
167,1059,3,"Ford, Mr. Edward Watson",male,18.00,2,2,W./C. 6608,34.3750,NaN,S,0,Mr.
168,1060,1,"Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genevieve Fosdick)",female,NaN,0,0,17770,27.7208,NaN,C,1,Mrs.
169,1061,3,"Hellstrom, Miss. Hilda Maria",female,22.00,0,0,7548,8.9625,NaN,S,1,Miss.
170,1062,3,"Lithman, Mr. Simon",male,NaN,0,0,S.O./P.P. 251,7.5500,NaN,S,0,Mr.
171,1063,3,"Zakarian, Mr. Ortin",male,27.00,0,0,2670,7.2250,NaN,C,0,Mr.
172,1064,3,"Dyker, Mr. Adolf Fredrik",male,23.00,1,0,347072,13.9000,NaN,S,0,Mr.
173,1065,3,"Torfa, Mr. Assad",male,NaN,0,0,2673,7.2292,NaN,C,0,Mr.
174,1066,3,"Asplund, Mr. Carl Oscar Vilhelm Gustafsson",male,40.00,1,5,347077,31.3875,NaN,S,0,Mr.
175,1067,2,"Brown, Miss. Edith Eileen",female,15.00,0,2,29750,39.0000,NaN,S,1,Miss.
176,1068,2,"Sincock, Miss. Maude",female,20.00,0,0,C.A. 33112,36.7500,NaN,S,1,Miss.
177,1069,1,"Stengel, Mr. Charles Emil Henry",male,54.00,1,0,11778,55.4417,C116,C,0,Mr.
178,1070,2,"Becker, Mrs. Allen Oliver (Nellie E Baumgardner)",female,36.00,0,3,230136,39.0000,F4,S,1,Mrs.
179,1071,1,"Compton, Mrs. Alexander Taylor (Mary Eliza Ingersoll)",female,64.00,0,2,PC 17756,83.1583,E45,C,1,Mrs.
180,1072,2,"McCrie, Mr. James Matthew",male,30.00,0,0,233478,13.0000,NaN,S,0,Mr.
181,1073,1,"Compton, Mr. Alexander Taylor Jr",male,37.00,1,1,PC 17756,83.1583,E52,C,0,Mr.
182,1074,1,"Marvin, Mrs. Daniel Warner (Mary Graham Carmichael Farquarson)",female,18.00,1,0,113773,53.1000,D30,S,1,Mrs.
183,1075,3,"Lane, Mr. Patrick",male,NaN,0,0,7935,7.7500,NaN,Q,0,Mr.
184,1076,1,"Douglas, Mrs. Frederick Charles (Mary Helene Baxter)",female,27.00,1,1,PC 17558,247.5208,B58 B60,C,1,Mrs.
185,1077,2,"Maybery, Mr. Frank Hubert",male,40.00,0,0,239059,16.0000,NaN,S,0,Mr.
186,1078,2,"Phillips, Miss. Alice Frances Louisa",female,21.00,0,1,S.O./P.P. 2,21.0000,NaN,S,1,Miss.
187,1079,3,"Davies, Mr. Joseph",male,17.00,2,0,A/4 48873,8.0500,NaN,S,0,Mr.
188,1080,3,"Sage, Miss. Ada",female,NaN,8,2,CA. 2343,69.5500,NaN,S,1,Miss.
189,1081,2,"Veal, Mr. James",male,40.00,0,0,28221,13.0000,NaN,S,0,Mr.
190,1082,2,"Angle, Mr. William A",male,34.00,1,0,226875,26.0000,NaN,S,0,Mr.
191,1083,1,"Salomon, Mr. Abraham L",male,NaN,0,0,111163,26.0000,NaN,S,0,Mr.
192,1084,3,"van Billiard, Master. Walter John",male,11.50,1,1,A/5. 851,14.5000,NaN,S,0,Master.
193,1085,2,"Lingane, Mr. John",male,61.00,0,0,235509,12.3500,NaN,Q,0,Mr.
194,1086,2,"Drew, Master. Marshall Brines",male,8.00,0,2,28220,32.5000,NaN,S,0,Master.
195,1087,3,"Karlsson, Mr. Julius Konrad Eugen",male,33.00,0,0,347465,7.8542,NaN,S,0,Mr.
196,1088,1,"Spedden, Master. Robert Douglas",male,6.00,0,2,16966,134.5000,E34,C,0,Master.
197,1089,3,"Nilsson, Miss. Berta Olivia",female,18.00,0,0,347066,7.7750,NaN,S,1,Miss.
198,1090,2,"Baimbrigge, Mr. Charles Robert",male,23.00,0,0,C.A. 31030,10.5000,NaN,S,0,Mr.
199,1091,3,"Rasmussen, Mrs. (Lena Jacobsen Solvang)",female,NaN,0,0,65305,8.1125,NaN,S,1,Mrs.
200,1092,3,"Murphy, Miss. Nora",female,NaN,0,0,36568,15.5000,NaN,Q,1,Miss.
201,1093,3,"Danbom, Master. Gilbert Sigvard Emanuel",male,0.33,0,2,347080,14.4000,NaN,S,0,Master.
202,1094,1,"Astor, Col. John Jacob",male,47.00,1,0,PC 17757,227.5250,C62 C64,C,0,Col.
203,1095,2,"Quick, Miss. Winifred Vera",female,8.00,1,1,26360,26.0000,NaN,S,1,Miss.
204,1096,2,"Andrew, Mr. Frank Thomas",male,25.00,0,0,C.A. 34050,10.5000,NaN,S,0,Mr.
205,1097,1,"Omont, Mr. Alfred Fernand",male,NaN,0,0,F.C. 12998,25.7417,NaN,C,0,Mr.
206,1098,3,"McGowan, Miss. Katherine",female,35.00,0,0,9232,7.7500,NaN,Q,1,Miss.
207,1099,2,"Collett, Mr. Sidney C Stuart",male,24.00,0,0,28034,10.5000,NaN,S,0,Mr.
208,1100,1,"Rosenbaum, Miss. Edith Louise",female,33.00,0,0,PC 17613,27.7208,A11,C,1,Miss.
209,1101,3,"Delalic, Mr. Redjo",male,25.00,0,0,349250,7.8958,NaN,S,0,Mr.
210,1102,3,"Andersen, Mr. Albert Karvin",male,32.00,0,0,C 4001,22.5250,NaN,S,0,Mr.
211,1103,3,"Finoli, Mr. Luigi",male,NaN,0,0,SOTON/O.Q. 3101308,7.0500,NaN,S,0,Mr.
212,1104,2,"Deacon, Mr. Percy William",male,17.00,0,0,S.O.C. 14879,73.5000,NaN,S,0,Mr.
213,1105,2,"Howard, Mrs. Benjamin (Ellen Truelove Arman)",female,60.00,1,0,24065,26.0000,NaN,S,1,Mrs.
214,1106,3,"Andersson, Miss. Ida Augusta Margareta",female,38.00,4,2,347091,7.7750,NaN,S,1,Miss.
215,1107,1,"Head, Mr. Christopher",male,42.00,0,0,113038,42.5000,B11,S,0,Mr.
216,1108,3,"Mahon, Miss. Bridget Delia",female,NaN,0,0,330924,7.8792,NaN,Q,1,Miss.
217,1109,1,"Wick, Mr. George Dennick",male,57.00,1,1,36928,164.8667,NaN,S,0,Mr.
218,1110,1,"Widener, Mrs. George Dunton (Eleanor Elkins)",female,50.00,1,1,113503,211.5000,C80,C,1,Mrs.
219,1111,3,"Thomson, Mr. Alexander Morrison",male,NaN,0,0,32302,8.0500,NaN,S,0,Mr.
220,1112,2,"Duran y More, Miss. Florentina",female,30.00,1,0,SC/PARIS 2148,13.8583,NaN,C,1,Miss.
221,1113,3,"Reynolds, Mr. Harold J",male,21.00,0,0,342684,8.0500,NaN,S,0,Mr.
222,1114,2,"Cook, Mrs. (Selena Rogers)",female,22.00,0,0,W./C. 14266,10.5000,F33,S,1,Mrs.
223,1115,3,"Karlsson, Mr. Einar Gervasius",male,21.00,0,0,350053,7.7958,NaN,S,0,Mr.
224,1116,1,"Candee, Mrs. Edward (Helen Churchill Hungerford)",female,53.00,0,0,PC 17606,27.4458,NaN,C,1,Mrs.
225,1117,3,"Moubarek, Mrs. George (Omine Amenia"" Alexander)""",female,NaN,0,2,2661,15.2458,NaN,C,1,Mrs.
226,1118,3,"Asplund, Mr. Johan Charles",male,23.00,0,0,350054,7.7958,NaN,S,0,Mr.
227,1119,3,"McNeill, Miss. Bridget",female,NaN,0,0,370368,7.7500,NaN,Q,1,Miss.
228,1120,3,"Everett, Mr. Thomas James",male,40.50,0,0,C.A. 6212,15.1000,NaN,S,0,Mr.
229,1121,2,"Hocking, Mr. Samuel James Metcalfe",male,36.00,0,0,242963,13.0000,NaN,S,0,Mr.
230,1122,2,"Sweet, Mr. George Frederick",male,14.00,0,0,220845,65.0000,NaN,S,0,Mr.
231,1123,1,"Willard, Miss. Constance",female,21.00,0,0,113795,26.5500,NaN,S,1,Miss.
232,1124,3,"Wiklund, Mr. Karl Johan",male,21.00,1,0,3101266,6.4958,NaN,S,0,Mr.
233,1125,3,"Linehan, Mr. Michael",male,NaN,0,0,330971,7.8792,NaN,Q,0,Mr.
234,1126,1,"Cumings, Mr. John Bradley",male,39.00,1,0,PC 17599,71.2833,C85,C,0,Mr.

# References

The references to the blog posts below may be helpful in your deeper delve into the universe of AutoViz

* Pandas Profiling GitHub - https://github.com/pandas-profiling/pandas-profiling
* Dan Roth, AutoViz: A New Tool for Automated Visualization - https://towardsdatascience.com/autoviz-a-new-tool-for-automated-visualization-ec9c1744a6ad
* George Vyshnya, PROs and CONs of Rapid EDA Tools - https://medium.com/sbc-group-blog/pros-and-cons-of-rapid-eda-tools-e1ccd159ab07
* SweetViz - https://towardsdatascience.com/sweetviz-automated-eda-in-python-a97e4cabacde
* DataPrep - https://sfu-db.github.io/dataprep/user_guide/eda/plot.html